




.build/mega2560/src/halleffect.cpp : src/halleffect.ino
	@mkdir -p .build/mega2560/src
	@echo [93msrc/halleffect.ino[0m
	@/usr/bin/ino preproc  -o $@ $^


all : .build/mega2560/src/halleffect.cpp
	@true

